# Generated by Django 4.1 on 2023-03-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginn', '0008_remove_quiz_q_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='q_name',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
