# Generated by Django 4.1 on 2023-03-18 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginn', '0010_alter_quiz_q_score_alter_quiz_q_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='q_name',
        ),
    ]
