# Generated by Django 4.1 on 2023-03-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginn', '0011_remove_quiz_q_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_name', models.CharField(default='NULL', max_length=255)),
                ('q1', models.CharField(default='Null', max_length=255)),
                ('op1_1', models.CharField(default='Null', max_length=255)),
                ('op2_1', models.CharField(default='Null', max_length=255)),
                ('op3_1', models.CharField(default='Null', max_length=255)),
                ('op4_1', models.CharField(default='Null', max_length=255)),
                ('ans_1', models.CharField(default='Null', max_length=255)),
                ('q2', models.CharField(default='Null', max_length=255)),
                ('op1_2', models.CharField(default='Null', max_length=255)),
                ('op2_2', models.CharField(default='Null', max_length=255)),
                ('op3_2', models.CharField(default='Null', max_length=255)),
                ('op4_2', models.CharField(default='Null', max_length=255)),
                ('ans_2', models.CharField(default='Null', max_length=255)),
                ('q3', models.CharField(default='Null', max_length=255)),
                ('op1_3', models.CharField(default='Null', max_length=255)),
                ('op2_3', models.CharField(default='Null', max_length=255)),
                ('op3_3', models.CharField(default='Null', max_length=255)),
                ('op4_3', models.CharField(default='Null', max_length=255)),
                ('ans_3', models.CharField(default='Null', max_length=255)),
            ],
        ),
    ]
