# Generated by Django 4.1 on 2023-03-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginn', '0015_user_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
